// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI4kzdwG-MPp2EijvVPDNpma3lJMgxN-E',
    appId: '1:648987104114:web:273436c13d1b70d0fa83eb',
    messagingSenderId: '648987104114',
    projectId: 'scan-gourmet',
    authDomain: 'scan-gourmet.firebaseapp.com',
    storageBucket: 'scan-gourmet.appspot.com',
    measurementId: 'G-20H9V90E1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkgJi9RYVNimzYF4sjWBqoIsGP9HrJ-k',
    appId: '1:648987104114:android:4a4c53d16892b46ffa83eb',
    messagingSenderId: '648987104114',
    projectId: 'scan-gourmet',
    storageBucket: 'scan-gourmet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpRtFQbbTRuVQ64XcURQwRjhu1QIRY7WU',
    appId: '1:648987104114:ios:30cfa6a891ce67d8fa83eb',
    messagingSenderId: '648987104114',
    projectId: 'scan-gourmet',
    storageBucket: 'scan-gourmet.appspot.com',
    androidClientId:
        '648987104114-70lmtjr8uuhiqfrjpbgj60cuq2kllum2.apps.googleusercontent.com',
    iosClientId:
        '648987104114-llub4qtitpu9ie6ubnmqm0irj1hg545i.apps.googleusercontent.com',
    iosBundleId: 'com.scangourmet',
  );
}
